name: Test
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - uses: abatilo/actions-poetry@v2.0.0
        with:
            poetry-version: 1.1.0
      - name: Install all of the dependencies
        run: |
          poetry install
      - name: Run test
        run: |
          poetry run pytest tests/ -v
